### ISSUE TITLE
PyYAML dependency version

### ISSUE THREAD

**Issue by cmarxer** [pferreir/pyssb#11]
In `setup.py` the dependency `PyYAML` is fixed to version `3.12`. I have troubles installing this specific version (others like e.g. `3.13` work).

I wonder if there is a reason why exactly `3.12` is required or if newer versions are also fine?

**Comment by decentral1se** [comment]
Hi @cmarxer, thanks for reporting. The dependecy has been bumped now (see https://github.com/pferreir/pyssb/blob/master/setup.py#L52) and has a less restrictive bound. Hope that is solved for now :+1:
